#!/bin/bash
# The logic to stop your application should be put in this script.

INSTALL_DIR=${OPENSHIFT_HOMEDIR}app-root/runtime

echo "Stopping teamcity."
kill -QUIT `cat ${INSTALL_DIR}/teamcity/run/teamcity.pid`

exit 0